net/qrtr: fix missing 'work' member
causing error like this:
../net/qrtr/qrtr.c:423:26: error: no member named 'work' in 'struct qrtr_node'
        cancel_work_sync(&node->work);
                          ~~~~  ^